version: '3.8'

services:
    dev:
        container_name: blankspace-dev
        image: blankspace-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: yarn start:dev
        ports:
            - 3001:3001
        networks:
            - blankspace
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: blankspace-prod
        image: blankspace-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: yarn start:prod
        ports:
            - 3001:3001
        networks:
            - blankspace
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    blankspace: